---
# Python CircleCI 2.0 configuration file
#
# INFO: Check CircleCI documentation for more details
#       https://circleci.com/docs/2.0/language-python/

version: 2.1


jobs:
  lint:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6

    steps:
      - checkout

      - restore_cache:
          # Increasingly general patterns to restore
          # https://circleci.com/docs/2.0/caching/#using-keys-and-templates
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-cache-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Install Python packages
          command: make sync

      - save_cache:
          # Pipenv venv and pip cached wheels
          paths:
            - "~/.local"
            - "~/.cache"
          key: pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run linters
          command: make lint


  test:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-cache-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Install Python packages
          command: make sync

      - save_cache:
          paths:
            - "~/.local"
            - "~/.cache"
          key: pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run unit tests
          command: make test


workflows:
  version: 2

  test-build-deploy:
    jobs:
      - lint
      - test
